name: rsync-server

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 7 * * 1'  # every monday at 7:00 https://crontab.guru/#0_7_*_*_1

jobs:
  image:
    name: rsync-server
    runs-on: ubuntu-20.04
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.2.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "🛠️ Docker QEMU"
        run: make qemu
      - name: "🛠️ Build and 📤 Upload to hub.docker.com"
        run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            make all
      - name: "🧹 Clean"
        run: make clean