name: rsync-server

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 7 * * 1'  # every monday at 7:00 https://crontab.guru/#0_7_*_*_1
  workflow_dispatch:
jobs:
  image:
    name: rsync-server
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.4.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "🛠️ Bash check"
        run: find . -type f -name "*.sh" -exec bash -n {} \;
      - name: "🛠️ Docker QEMU"
        run: make qemu
      - name: "🛠️ Build and 📤 Upload to hub.docker.com"
        run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            make all
      - name: "🧹 Clean"
        run: make clean
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        min_quality_grade: 'WARNING'
        min_quality_score: '20'
        max_defects_rate: '0.2'
        max_complex_functions_rate: '0.2'
        max_long_functions_rate: '0.2'
        project_name: ''
        max_timeout_sec: '600'
